theme: jekyll-theme-minimal
title: Talia Kusmirek
description: Hi, I'm Talia Kusmirek. I am a student at Boston College who is consistently learning and challenging myself in all aspects of my career. Learn more about what I've done, what I'm doing, and what I'm planning next here.
